### ISSUE TITLE
Have you considered using HAPI FHIR ...?

### ISSUE THREAD

**Issue by jkiddo** [C3-PRO/c3-pro-ios-framework#2]
As done here https://github.com/botunge/hapi-fhir using j2objc

**Comment by p2** [comment]
Well, we are working on the corresponding [Android framework](https://github.com/C3-PRO/c3-pro-android-framework) if that's what you need?

**Comment by jkiddo** [comment]
I'm not that into iOS, but I've heard some successful stories porting the Java business logic from HAPI FHIR into iOS using j2objc in order to streamline the use of FHIR API's across platforms

**Comment by p2** [comment]
We use the iOS native [Swift FHIR library](https://github.com/smart-on-fhir/Swift-FHIR) for that. ;)

More specifically, the [Swift-SMART](https://github.com/smart-on-fhir/Swift-SMART) framework which incorporates Swift-FHIR and adds all the server connection logic. Similar to HAPI.

**Comment by jkiddo** [comment]
Well, in that case there might not be any incentive to do any porting ;)

**Comment by p2** [comment]
Indeed not! A good thing given my virtually inexistent experience with Java. 👍🏼
