### ISSUE TITLE
Questionnaire Sample Code won't function properly as written

### ISSUE THREAD

**Issue by conanm** [C3-PRO/c3-pro-ios-framework#3]
Hi, using this code: 

``` swift
// Let's assume you have a Questionnaire "Survey.json" in your app bundle
// You can use other means, such as `Questionnaire.read(id:server:callback:)`
let questionnaire = NSBundle.mainBundle().fhir_bundledResource("<# Survey #>")
let controller = QuestionnaireController(questionnaire: questionnaire)
controller.whenCompleted = { viewController, answers in
    viewController.dismissViewControllerAnimated(true, completion: nil)
    // `answers` is a FHIR "QuestionnaireResponse" resource if not nil
    if let answers = answers {
        // e.g. send to a SMART server:
        answers.create(<# smart.server #>) { error in
            // check if `error` is not nil and handle
        }
    }
}
```

Let's say in a function or somesuch, seems to be the case that the 'controller' instance (unless stored as an ivar in an instance of a class, as in the demo examples) won't be retained and therefore the callsbacks `whenCompleted` and `whenCancelledOrFailed` never fire because the ORKResearchTask object's delegate property becomes nil. I am able to solve this problem simply by keeping a reference to any allocated QuestionnaireControllers.

**Comment by p2** [comment]
You are absolutely correct, I will fix the sample code. Thanks!
